### ISSUE TITLE
添加prometheus_exporter

### ISSUE THREAD

**Issue by huanjoyous** [mao303mao/locust-http#11]
你好作者，
1，你现在持久化是怎么实现的
2，在测试api接口的时候，服务器的各个性能参数你现在是监控的指标的呢（）
3，希望更新Locust

疑问:
结合其他Locust版本有什么区别呢

**Comment by mao303mao** [comment]
> 你好作者， 1，你现在持久化是怎么实现的 2，在测试api接口的时候，服务器的各个性能参数你现在是监控的指标的呢（） 3，希望更新Locust
> 
> 疑问: 结合其他Locust版本有什么区别呢

1-持久化：比较早期的版本是做了推送普罗米修斯+grafana的处理的，这个网上也有不少资料。但后来locust支持报告下载后，这部分功能就用的不多了，然后随着locust的升级，要改的地方不少，就懒了
2-监控服务端指标，我写的一个监控小应用（web），比较简陋不分享了。
主要是：服务端安装glances，利用glances的http接口获取服务端的指标。这个监控小应用每隔3s获取一次指标信息，利用websokcet推送到浏览器端（vue+echarts）
3-因为目前我这里locust的这个版本用的还行，就没升级locust的动力了，见谅。
