### ISSUE TITLE
arm64编译，Version 3.0 received does match expected version 3.1

### ISSUE THREAD

**Issue by huanjoyous** [mao303mao/locust-http#12]
参考https://github.com/myzhan/boomer/issues/105我依然没有解决
![image](https://user-images.githubusercontent.com/28851617/139638097-e82a505a-ab3b-4b4a-9ca4-e66ab2154afa.png)

**Comment by mao303mao** [comment]
readme中我已经说明了：
worker会遇到报错：error gomq/zmtp: Got error while receiving greeting: Version 3.0 received does match expected version 3.1 
    解决方法：修改 mod\github.com\zeromq\gomq\zmtp\protocol.go 中的minorVersion uint8 = 1 改成 0

**Comment by mao303mao** [comment]
> 参考[https://github.com/myzhan/boomer/issues/105我依然没有解决](https://github.com/myzhan/boomer/issues/105%E6%88%91%E4%BE%9D%E7%84%B6%E6%B2%A1%E6%9C%89%E8%A7%A3%E5%86%B3) ![image](https://user-images.githubusercontent.com/28851617/139638097-e82a505a-ab3b-4b4a-9ca4-e66ab2154afa.png)
worker会遇到报错：error gomq/zmtp: Got error while receiving greeting: Version 3.0 received does match expected version 3.1 
    解决方法：修改 mod\github.com\zeromq\gomq\zmtp\protocol.go 中的minorVersion uint8 = 1 改成 0

**Comment by mao303mao** [comment]
看一下，是不是就好了

**Comment by huanjoyous** [comment]
我改了低版本依赖，现在无法复现了
