### ISSUE TITLE
无法执行二进制文件

### ISSUE THREAD

**Issue by gegelaopiaoke** [mao303mao/locust-http#13]
boomerHazardServer: cannot execute binary file

-rwxr--r-- 1 root root 26832647 Nov 13 14:21 boomerHazardServer。已经给了权限

**Comment by mao303mao** [comment]
兄弟，你是读写权限。。。。。
要执行权限

**Comment by mao303mao** [comment]
请问你的linux版本？
我本机linux 64位测试ok。
![image](https://user-images.githubusercontent.com/37785668/142964814-d3ad5ed5-7839-48ab-ad6a-38c6ad8f4432.png)

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/142965533-529ad4fc-1382-4e5c-9272-b4e08bc9354b.png)
大哥，你看看？我给了权限，liunx版本和您一致，还是提示boomerHazardServer: boomerHazardServer: cannot execute binary file

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/142965860-8faea812-d4be-46b2-8d90-ac9af51cfd81.png)
大佬您好，我的服务器版本和您的一致，权限我也给了，还是提示那个哦

**Comment by gegelaopiaoke** [comment]
大佬。我自己解决了。。是我执行指令错了。抱歉
应该是./boomerHazardServer -EtcdAddr 192.168.23.222:2379 -Host 压力器自己的ip -Port 3000
