### ISSUE TITLE
提交事务提示缺少json

### ISSUE THREAD

**Issue by gegelaopiaoke** [mao303mao/locust-http#14]
![image](https://user-images.githubusercontent.com/29562144/142969764-2aab3462-ea99-46d8-aebe-707cf426c9d9.png)
大佬能请教下，这个json文件要怎么生成么，我提交事务的时候提示缺少这个json

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/142969875-65ceb80f-2199-4314-b01f-9085bc6b1ff7.png)

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/142970955-4aa58ea4-61d8-4d5f-abeb-459755399221.png)
我导入事务也提示没有那个./JSONS文件，大佬是不是您少上传了，我检查了下您的源码 也没这个目录

**Comment by gegelaopiaoke** [comment]
我自己新建目录创建了JSONS文件夹，也新建了main.json和tmp.json,执行事务的时候提示Expecting value: line 1 column 1 (char 0)

**Comment by gegelaopiaoke** [comment]
大哥方便给个联系方式么

**Comment by mao303mao** [comment]
奇怪啊，我记得一直有个空的jsons的文件夹的，怎么没有了。。。
这里只要有个空的jsons文件夹就可以了

**Comment by gegelaopiaoke** [comment]
> 奇怪啊，我记得一直吐空的jsons的文件夹的，怎么没有了。。。 这里只要吐空的jsons文件夹就可以了

大佬。不行。也不会新建文件，必须我自己新建 那2个文件才行。那个报错您有遇见过么

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/142980902-06e63584-7b1e-4557-98f1-fc980cb65612.png)
![image](https://user-images.githubusercontent.com/29562144/142980921-96c57d8f-499f-4b03-8a5d-db281d3ee41e.png)
拉您最新的代码，会提示json中没有MainTask，但是您看我的json里面明明有

**Comment by mao303mao** [comment]
你的jsons文件夹怎么有两个路径

**Comment by gegelaopiaoke** [comment]
> 你的jsons文件夹怎么有两个路径

![image](https://user-images.githubusercontent.com/29562144/142981576-02f76f34-1154-4c86-9fa0-18f6fbc0e0af.png)
忘记删了。现在我的目录事这样。json里面的内容保存事物后会自动生成，tmp里面会生成数据。main.json还是没内容。执行的时候还是提示没有maintask

**Comment by mao303mao** [comment]
要先保存事务

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/142982573-c0410763-b397-426b-80fd-c6527f76c31a.png)
兄弟。能给个联系方式么，付费求解决，我需要您的项目

**Comment by gegelaopiaoke** [comment]
重置后提交。提示这个

**Comment by mao303mao** [comment]
很奇怪，我本地这里重置没这边报错

具体操作是啥

**Comment by gegelaopiaoke** [comment]
> 

1.全部重置
2.新建事务
3.保存
4.提交事务
5.连接服务器异常

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/142983277-36ad83f4-fd6f-47cb-b5a1-d5681184d925.png)
感觉压力机那边都没进服务

**Comment by mao303mao** [comment]
你的命令有问题

**Comment by gegelaopiaoke** [comment]
请指教。。死在哪里

**Comment by mao303mao** [comment]
boomerHazardServer -EtcdAddr etcd的ip:2379 -Host 压力器自己的ip -Port

**Comment by gegelaopiaoke** [comment]
大佬，感谢，我现在还一个问题，您的使用教程里面这个workya要怎么用，能指点下么
![image](https://user-images.githubusercontent.com/29562144/142984509-1e0d1df4-fc58-4e5e-a757-6c54832846d2.png)

**Comment by gegelaopiaoke** [comment]
![Uploading image.png…]()

**Comment by gegelaopiaoke** [comment]
2021/11/23 15:18:26 boomer.go:196: Timeout waiting for sending quit message to master, boomer will quit any way.
{1 0xa07e80 登录接口}
2021/11/23 15:19:02 client_gomq.go:27: Boomer is built with gomq support.
2021/11/23 15:19:02 runner.go:431: Failed to connect to master(172.20.1.175:5557) with error gomq/zmtp: Got error while receiving greeting: Version 3.1 received does match expected version 3.0
我是不是把什么东西版本弄错了

**Comment by mao303mao** [comment]
解决方案1：使用我打包好的boomer，压测机管理页面上可直接下载
解决方案2：read me有所解决方案，这个是原版boomer和locust的版本不匹配。

**Comment by gegelaopiaoke** [comment]
> 解决方案1：使用我打包好的worker端服务，压测机管理页面上可直接下载 解决方案2：如果是自己编译workder端服务，readme中有解决方案，这个是因为boomer和locust的版本不匹配（boomer好久没更新了）。
> 
> “在页面上提交事务，worker会遇到报错：error gomq/zmtp: Got error while receiving greeting: Version 3.0 received does match expected version 3.1 ”
> 
> 解决方法：修改 mod\github.com\zeromq\gomq\zmtp\protocol.go 中的minorVersion uint8 = 1 改成 0

大佬，我可以确认。我用的是您管理界面下载的liunx的，提示版本不对

**Comment by mao303mao** [comment]
我重新打包一个新的

**Comment by gegelaopiaoke** [comment]
没有的。
![image](https://user-images.githubusercontent.com/29562144/142987223-0c75ee59-4728-49ee-91be-17f4fba10d40.png)
用的就是您指定的1.2.3

**Comment by mao303mao** [comment]
那就奇怪了，不关了，原来提供下载还是去年的了，一直没有更新。
我重新打包了新的，刚刚测试了下本机没问题，已经上传了。

另外这个项目是个模型性质的，后面应该不会加功能了，除非有bug修复，见谅

**Comment by gegelaopiaoke** [comment]
大佬您好，用了您最新的。还是版本不对，是我本地环境问题么

**Comment by gegelaopiaoke** [comment]
![Uploading image.png…]()
我本机部署也是提示版本不对

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/142994768-e4df6a8d-d2b6-4bdd-a208-ac936865816e.png)
本地部署也是不对。提示版本错误

**Comment by mao303mao** [comment]
解决方法：修改 mod\github.com\zeromq\gomq\zmtp\protocol.go 中的minorVersion uint8 = 1 改成 0

**Comment by gegelaopiaoke** [comment]
-。- 我的还是1.我自己改成0编译下把

**Comment by gegelaopiaoke** [comment]
大佬。我解决了。编译的时候还会有个坑，您的源码里面，有个地方go modue的时候 会报错，是多了一个网址，删了就好了，感谢您的指点，我现在跑起来了
