### ISSUE TITLE
【使用疑惑】事务参数化

### ISSUE THREAD

**Issue by gegelaopiaoke** [mao303mao/locust-http#15]
请教下大佬，能给个例子或者教程么，有点没明白如何让hander共享，以及参数化，以及签名校验。如果您的项目目前不打算加这块的功能就算了，辛苦了

**Comment by mao303mao** [comment]
参数化有对应功能，主要用于前一个请求获取token（在前置处理或每个事物的前置处理的保存参数操作），给后续主事务请求作为参数使用。

校验就比较简单粗暴了，毕竟是性能测试
