### ISSUE TITLE
保存数据丢失

### ISSUE THREAD

**Issue by gegelaopiaoke** [mao303mao/locust-http#16]
![image](https://user-images.githubusercontent.com/29562144/143035833-72782dc3-6445-4b6b-9e43-e6f0620aab25.png)
![image](https://user-images.githubusercontent.com/29562144/143035871-3883c0e4-0606-4ae5-86d8-426f835adf89.png)
大佬，保存后 main.json文件的参数丢失，HHeaders的参数丢了好多，只有一个uid

**Comment by gegelaopiaoke** [comment]
{
    "isSession": true,
    "HttpProxy": "",
    "PreTask": null,
    "MainTask": [
        {
            "TaskWeight": 1,
            "TaskName": "\u4e66\u7c4d\u641c\u7d22",
            "PreWork": null,
            "TestWork": {
                "Method": "Post",
                "UrlPath": "http://dev_projecty_api.stardustworld.cn",
                "Headers": {
                    "uid": "99772072",
                    "channelId": "AVG20001",
                    "ts": "999999999",
                    "apiVersion": "1.0.10",
                    "session": "6f7e07619de19fa00390f47a126d2ff8",
                    "lang": "en",
                    "devId": "866051035791041",
                    "sign": "e347f38063c966385d0c3d026541b6b1",
                    "clientVer": "1.1.00"
                },
                "Params": {
                    "secret": "20202020666",
                },
                "DictData": {
                    "keyword": "will",
                    "page": "1",
                    "limit": "10"
                },
                "RawData": "",
                "JsonData": "",
                "AssertChain": null,
                "SaveParamChain": null
            }
        }
    ]
}

**Comment by gegelaopiaoke** [comment]
[backup_1637675195.846924.json.zip](https://github.com/mao303mao/locust-http/files/7588516/backup_1637675195.846924.json.zip)
您可以试试我的这个json文件，导入进去后保存在本地看看您的main.JSON是否有数据丢失

**Comment by gegelaopiaoke** [comment]
目前我这边是百分之百复现，header的值丢失。parm的值丢失

**Comment by mao303mao** [comment]
确认是导入的一个bug，等我修复

**Comment by mao303mao** [comment]
已经修复
