### ISSUE TITLE
【Bug】事务异常

### ISSUE THREAD

**Issue by gegelaopiaoke** [mao303mao/locust-http#17]
![image](https://user-images.githubusercontent.com/29562144/143198333-0eaaf981-0a2c-4de1-a665-6b9f58c53a03.png)
![image](https://user-images.githubusercontent.com/29562144/143198360-1adf56ee-b98f-4b61-b1be-5c2a555dd435.png)
我这里只有一个事务，实时统计里面还有有多个

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/143196619-906d0d57-f387-43cf-878f-120f1b2e5fce.png)
![image](https://user-images.githubusercontent.com/29562144/143196633-1491d2f2-98e1-4d2a-836b-050d215d9f59.png)
40秒的时候都已经停止l了这里的图表还在刷新

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/143196753-46f685c0-38fd-4e50-95e2-64504e358d81.png)
而且还停止不了事务

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/143196863-9038e1f8-5799-4073-b96a-6946523fb6d3.png)
100个用户  30秒  每秒递增1个。。性能是否使用的有点过高 ？

**Comment by gegelaopiaoke** [comment]
![image](https://user-images.githubusercontent.com/29562144/143197718-e0fb242a-449f-4829-8515-0c55d00daf43.png)
我设置30秒  貌似不会停止

**Comment by gegelaopiaoke** [comment]
给我的感觉是要刷新浏览器才行。读的貌似是缓存的？您如果需要复现的话。请按照以下步骤
1.创建 2个事务后跑1次任务
2.删掉一个事务后保存，全部重置后提交
3.在实时统计里面查看事务列表，看看是1个事务还是2个事务

**Comment by mao303mao** [comment]
这个是locust原有就这样，locust的实时图表是缓存到浏览器器中的。
所以我在上面加了重置统计的按钮
