### ISSUE TITLE
【Bug】事务导入bug，导致除了第一个事务，其他所有事务的Method为Get

### ISSUE THREAD

**Issue by gegelaopiaoke** [mao303mao/locust-http#18]
大佬您好，导入的json文件。只有第一个事务的是post，其他的事务导入后会自动变成get，但是页面显示为get，该bug必现
![image](https://user-images.githubusercontent.com/29562144/143199344-83c11498-7619-4903-b58d-292b43cfe74a.png)
![image](https://user-images.githubusercontent.com/29562144/143199390-c4c1834f-5cfc-4696-a85b-2c1538999886.png)

**Comment by gegelaopiaoke** [comment]
main.json和tmp.json都是 post，但页面显示为get

**Comment by mao303mao** [comment]
没有复现，更新代码看看
![1](https://user-images.githubusercontent.com/37785668/143210991-d4e22931-1e3d-4b16-8596-78da4e224b8f.gif)

**Comment by gegelaopiaoke** [comment]
![2021-11-25 10 29 08](https://user-images.githubusercontent.com/29562144/143367848-b5ae4fe6-c024-420f-994e-3c9aaf037e45.gif)
大佬，按照您说的，我已经重置过很多次了，右上角也重置过，这个还是locust自带问题么？我只想跑1个事务，结果还是出现10个

**Comment by mao303mao** [comment]
你检查下保存后的main.json里面是几个事务。

**Comment by gegelaopiaoke** [comment]
找到原因了，是我自己的问题，检查了下您昨天的回复，jsons文件夹我外层还有一个。。。

想再请教1个问题，为什么总用户10，孵化率1，跑30秒，结果居然是5451
![image](https://user-images.githubusercontent.com/29562144/143377857-2c5c20c4-1186-4cfd-a645-0d2d4870f201.png)
这个能抽空讲解下？

**Comment by gegelaopiaoke** [comment]
![2021-11-25 12 03 43](https://user-images.githubusercontent.com/29562144/143378068-ac3e7258-daa0-42e5-8a7c-4aafef899900.gif)
有点不明白请求数怎么会这么多

**Comment by mao303mao** [comment]
那个是请求总数数5451,rps是257.
因为每个vuser的http接口是**不断循环**的跑的，直到停止。
所以很正常啊，你可以设置一个代理到fiddler上看看总请求数是否一致。这个是locust自带的计数器
