### ISSUE TITLE
windows做压测机提示异常

### ISSUE THREAD

**Issue by gegelaopiaoke** [mao303mao/locust-http#20]
![image](https://user-images.githubusercontent.com/29562144/143668397-3c45d41d-772e-4bcd-bc11-9095855d0902.png)
请教下打扰，为什么在liunx上能正常，在windows压测及这里会提示服务器异常，workerl都是我自己单独打的。

**Comment by mao303mao** [comment]
你的windows的ip是172.20.2.74吗，还有是否有防火墙
