### ISSUE TITLE
boomerHazardSer待机状态，占用cpu使用率

### ISSUE THREAD

**Issue by huanjoyous** [mao303mao/locust-http#6]
【操作】
长时间没有使用，用supervisord挂后台
【现象】
请问一下，你有这种现象没
![image](https://user-images.githubusercontent.com/28851617/93543819-1e2b1180-f98f-11ea-9244-1ffb5ddfc86e.png)

**Comment by mao303mao** [comment]
服务端（python那个web服务是常起的），客户端（boomer端）一般我用的时候才启动这个，没出现这个现象。
是否已经重置了，也就是断开和locust的连接...(长时间不用建议重置掉)。

boomer端重置状态下，一般只有个rgpc服务和ectd之间的心跳检查，照道理不会cpu使用很高的，我需要测试下看看

**Comment by huanjoyous** [comment]
待机状态下：
还在调用client_gomq.go，是不是这个使cpu偏高啊？
![image](https://user-images.githubusercontent.com/28851617/94500652-7b964c80-0232-11eb-818f-cde4d44e7243.png)

**Comment by mao303mao** [comment]
client_gomq.go这个是locust+boomer原本的通信，没有去研究过此是否会造成CPU偏高
而且我本地测试过，没有出现这种情况。
另外我改过一个bug，boomer.Events.Subscribe( boomer:quit)的地方改成SubscribeOnce处理了，原本的方式会出现重复订阅情况，不知道是不是这个bug引起的。

**Comment by mao303mao** [comment]
补充下，boomer的原作者也修复了这个bug。你可以更新下boomer。
修复方式与我上面的一致：
![image](https://user-images.githubusercontent.com/37785668/94655622-79ff7e00-0331-11eb-9c1b-410e788e4f58.png)
