### ISSUE TITLE
golang依赖问题

### ISSUE THREAD

**Issue by huanjoyous** [mao303mao/locust-http#7]
请问一下，我的依赖不全编译出来的会有什么影响嘛？

github.com/kataras/iris/core/errors 的遗漏是errgroup么？

![image](https://user-images.githubusercontent.com/28851617/94384015-2c89e200-0174-11eb-8c8a-87465dba06dd.png)

.\boomerHazardServer.go:171:2: undefined: boomerCall.RegisterBoomerCallServiceServer

这个也要注释掉么？

**Comment by mao303mao** [comment]
红色区域不要注释掉，这个是protobu自动生成的gPRC注册服务方法。
![image](https://user-images.githubusercontent.com/37785668/94402073-214bac00-019e-11eb-98e7-1a3a40af17e4.png)
你检查import情况

**Comment by huanjoyous** [comment]
> 红色区域不要注释掉，这个是protobu自动生成的gPRC注册服务方法。您 检查进口情况，是否正确约会那个proto生成的go包。
> ![图片](https://user-images.githubusercontent.com/37785668/94402073-214bac00-019e-11eb-98e7-1a3a40af17e4.png)

![image](https://user-images.githubusercontent.com/28851617/94402731-00d02180-019f-11eb-9242-300f13c6deef.png)

这里没有导入没有错

**Comment by mao303mao** [comment]
你上面"locust_hazard/proto"用了proto别名了，你 171:2地方怎么是boomerCall.RegisterBoomerCallServiceServer

import不同：go是到包的，python是到文件

**Comment by huanjoyous** [comment]
![image](https://user-images.githubusercontent.com/28851617/94404726-08dd9080-01a2-11eb-83cf-2a90c42f3b50.png)

我对比一下，这次用的方式从新生成boomerCall.pb.go，丢失了依赖

这是为什么呢，是不能在你的boomerCall.proto 直接生成那个3个文件了么？

**Comment by mao303mao** [comment]
这个是不能的，这几个是grpc依赖包，需要自己去go get .......的。在readme文件中有说明：
"github.com/levigross/grequests"
"github.com/myzhan/boomer"
"go.etcd.io/etcd/v3/clientv3"
"golang.org/x/net/context"
"google.golang.org/grpc"
"google.golang.org/protobuf"

注意下：etcd这个包安装及导入很容易出现包冲突，需要自己去手动处理删除一些多余的包。我但是也是搞了很久，百度一下吧
